// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FileSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __FileSystem_h__
#define __FileSystem_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace FileSystem
{

class File;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::FileSystem::File>&);
::IceProxy::Ice::Object* upCast(::IceProxy::FileSystem::File*);

}

}

namespace FileSystem
{

class File;
bool operator==(const File&, const File&);
bool operator<(const File&, const File&);
::Ice::Object* upCast(::FileSystem::File*);
typedef ::IceInternal::Handle< ::FileSystem::File> FilePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::FileSystem::File> FilePrx;
void __patch(FilePtr&, const ::Ice::ObjectPtr&);

}

namespace FileSystem
{

typedef ::std::vector< ::Ice::Byte> ByteSeq;

}

namespace FileSystem
{

class Callback_File_receiveFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_File_receiveFile_Base> Callback_File_receiveFilePtr;

class Callback_File_sendFile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_File_sendFile_Base> Callback_File_sendFilePtr;

}

namespace IceProxy
{

namespace FileSystem
{

class File : virtual public ::IceProxy::Ice::Object
{
public:

    ::FileSystem::ByteSeq receiveFile(const ::std::string& name)
    {
        return receiveFile(name, 0);
    }
    ::FileSystem::ByteSeq receiveFile(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return receiveFile(name, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_receiveFile(const ::std::string& name, const ::IceInternal::Function<void (const ::FileSystem::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_receiveFile(name, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_receiveFile(const ::std::string& name, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_receiveFile(name, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_receiveFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::FileSystem::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_receiveFile(name, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_receiveFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_receiveFile(name, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_receiveFile(const ::std::string& name, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::FileSystem::ByteSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::FileSystem::ByteSeq&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::FileSystem::FilePrx __proxy = ::FileSystem::FilePrx::uncheckedCast(__result->getProxy());
                ::FileSystem::ByteSeq __ret;
                try
                {
                    __ret = __proxy->end_receiveFile(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::FileSystem::ByteSeq&)> _response;
        };
        return begin_receiveFile(name, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string& name)
    {
        return begin_receiveFile(name, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string& name, const ::Ice::Context& __ctx)
    {
        return begin_receiveFile(name, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string& name, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_receiveFile(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_receiveFile(name, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string& name, const ::FileSystem::Callback_File_receiveFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_receiveFile(name, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string& name, const ::Ice::Context& __ctx, const ::FileSystem::Callback_File_receiveFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_receiveFile(name, &__ctx, __del, __cookie);
    }

    ::FileSystem::ByteSeq end_receiveFile(const ::Ice::AsyncResultPtr&);
    
private:

    ::FileSystem::ByteSeq receiveFile(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_receiveFile(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq)
    {
        return sendFile(name, seq, 0);
    }
    bool sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context& __ctx)
    {
        return sendFile(name, seq, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_sendFile(name, seq, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendFile(name, seq, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_sendFile(name, seq, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendFile(name, seq, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::FileSystem::FilePrx __proxy = ::FileSystem::FilePrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_sendFile(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_sendFile(name, seq, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq)
    {
        return begin_sendFile(name, seq, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context& __ctx)
    {
        return begin_sendFile(name, seq, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendFile(name, seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendFile(name, seq, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::FileSystem::Callback_File_sendFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendFile(name, seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string& name, const ::FileSystem::ByteSeq& seq, const ::Ice::Context& __ctx, const ::FileSystem::Callback_File_sendFilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendFile(name, seq, &__ctx, __del, __cookie);
    }

    bool end_sendFile(const ::Ice::AsyncResultPtr&);
    
private:

    bool sendFile(const ::std::string&, const ::FileSystem::ByteSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sendFile(const ::std::string&, const ::FileSystem::ByteSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<File> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_secure(bool __secure) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_twoway() const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_oneway() const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_batchOneway() const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_datagram() const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_batchDatagram() const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_compress(bool __compress) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_timeout(int __timeout) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<File> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<File*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace FileSystem
{

class File : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::FileSystem::ByteSeq receiveFile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool sendFile(const ::std::string&, const ::FileSystem::ByteSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace FileSystem
{

class File : virtual public ::IceDelegate::FileSystem::File,
             virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::FileSystem::ByteSeq receiveFile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool sendFile(const ::std::string&, const ::FileSystem::ByteSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace FileSystem
{

class File : virtual public ::IceDelegate::FileSystem::File,
             virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::FileSystem::ByteSeq receiveFile(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool sendFile(const ::std::string&, const ::FileSystem::ByteSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace FileSystem
{

class File : virtual public ::Ice::Object
{
public:

    typedef FilePrx ProxyType;
    typedef FilePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::FileSystem::ByteSeq receiveFile(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___receiveFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool sendFile(const ::std::string&, const ::FileSystem::ByteSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sendFile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const File& l, const File& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const File& l, const File& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace FileSystem
{

template<class T>
class CallbackNC_File_receiveFile : public Callback_File_receiveFile_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::FileSystem::ByteSeq&);

    CallbackNC_File_receiveFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::FileSystem::FilePrx __proxy = ::FileSystem::FilePrx::uncheckedCast(__result->getProxy());
        ::FileSystem::ByteSeq __ret;
        try
        {
            __ret = __proxy->end_receiveFile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_File_receiveFilePtr
newCallback_File_receiveFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::FileSystem::ByteSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_File_receiveFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_File_receiveFilePtr
newCallback_File_receiveFile(T* instance, void (T::*cb)(const ::FileSystem::ByteSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_File_receiveFile<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_File_receiveFile : public Callback_File_receiveFile_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::FileSystem::ByteSeq&, const CT&);

    Callback_File_receiveFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::FileSystem::FilePrx __proxy = ::FileSystem::FilePrx::uncheckedCast(__result->getProxy());
        ::FileSystem::ByteSeq __ret;
        try
        {
            __ret = __proxy->end_receiveFile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_File_receiveFilePtr
newCallback_File_receiveFile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::FileSystem::ByteSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_File_receiveFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_File_receiveFilePtr
newCallback_File_receiveFile(T* instance, void (T::*cb)(const ::FileSystem::ByteSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_File_receiveFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_File_sendFile : public Callback_File_sendFile_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_File_sendFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::FileSystem::FilePrx __proxy = ::FileSystem::FilePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_sendFile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_File_sendFilePtr
newCallback_File_sendFile(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_File_sendFile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_File_sendFilePtr
newCallback_File_sendFile(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_File_sendFile<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_File_sendFile : public Callback_File_sendFile_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_File_sendFile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::FileSystem::FilePrx __proxy = ::FileSystem::FilePrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_sendFile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_File_sendFilePtr
newCallback_File_sendFile(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_File_sendFile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_File_sendFilePtr
newCallback_File_sendFile(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_File_sendFile<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
